var shinydemos = require('./lib/compiler').create;

console.log('NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN');
console.log('NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN');
console.log('NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN');
console.log('NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN');
console.log('NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN');
console.log('NNNNNNNNNNNNNms:.``.:smNNm-------:+hNNNNNNNNNNNNNN');
console.log('NNNNNNNNNNNNm-   --`  :mNm`  `..`   oNNNNNNNNNNNNN');
console.log('NNNNNNNNNNNNs   sNNy   hNd`  /NNm:  `dNNNNNNNNNNNN');
console.log('NNNNNNNNNNNNy   oNNmooodNm`  /NNN+  `dNNNNNNNNNNNN');
console.log('NNNNNNNNNNNNm:   +mNNNNNNm`  /NNN+  `dNNNNNNNNNNNN');
console.log('NNNNNNNNNNNNNm+`  `+dNNNNd`  /NNN+  `dNNNNNNNNNNNN');
console.log('NNNNNNNNNNNNNNNd+`  `+mNNd`  /NNN+  `dNNNNNNNNNNNN');
console.log('NNNNNNNNNNNNNNNNNm/   /mNd`  /NNN+  `dNNNNNNNNNNNN');
console.log('NNNNNNNNNNNNo..:mNN+   hNd`  /NNN+  `dNNNNNNNNNNNN');
console.log('NNNNNNNNNNNNo  `dNm+   hNd`  /mmd-  `mNNNNNNNNNNNN');
console.log('NNNNNNNNNNNNm-  `..   /mNm`   ``    oNNNNNNNNNNNNN');
console.log('NNNNNNNNNNNNNms/-..-/yNNNm:::::::/odNNNNNNNNNNNNNN');
console.log('NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN');
console.log('NNNNNNNNNNNNmmmmmmmmmmmmmmmmmmmmmmmmmmNNNNNNNNNNNN');
console.log('NNNNNNNNNNNNdoooooooooooooooooooooooodNNNNNNNNNNNN');
console.log('NNNNNNNNNNNNmhhhhhhhhhhhhhhhhhhhhhdhhmNNNNNNNNNNNN');
console.log('NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN');
console.log('NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN');
console.log('NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN');
console.log('NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN');

shinydemos();